include ../../vep_0/share/make_common.mk

USER_LIBS :=
USER_CFLAGS :=
USER_LINK_FLAGS :=
SOURCES += $(wildcard ./single/src/*.c)
HEADERS += $(wildcard ./single/inc/*.h)
include ../../vep_0/share/make_tile.mk
